export const SELECTORS = {
  login: {
    username: "[data-test=username]",
    password: "[data-test=password]",
    login_btn: "[data-test=login-button]",
    message_error: 'div[class*="error-message-container"]',
  },
  grid: {
    grid_list: "[data-test='inventory-list']",
    grid_item: "[data-test='inventory-item']",
    add_to_cart_btn: "[data-test='add-to-cart-sauce-labs-backpack']",
    remove_to_cart_btn: "[data-test='remove-sauce-labs-backpack']",
    grid_img: ".inventory_item_img",
    pug_img: "img[src*='sl-404.168b1cce.jpg']",
    backpack_img: "[data-test='inventory-item-sauce-labs-backpack-img']",
    product_name: "[data-test='inventory-item-name']",
    product_description: "[data-test='inventory-item-desc']",
    product_price: "[data-test='inventory-item-price']",
    img_detail: ".inventory_details_img",
    sort_items: "[data-test='product-sort-container']",
  },
  cart: {
    cart_btn: "[data-test='shopping-cart-link']",
    cart_badge: "[data-test='shopping-cart-badge']",
    checkout_btn: "[data-test='checkout']",
    back_btn: "[data-test='continue-shopping']",
    remove_product_btn: "[data-test='remove-sauce-labs-backpack']",
    cart_items: "[data-test='cart-list']",
    removed_item: ".removed_cart_item"
  },
  checkout: {
    first_name: "[data-test='firstName']",
    last_name: "[data-test='lastName']",
    zipcode: "[data-test='postalCode']",
    cancel_btn: "[data-test='cancel']",
    continue_btn: "[data-test='continue']",
    message_error: 'div[class*="error-message-container"]',
    finish_btn: "[data-test='finish']",
    checkout_complete: "[data-test='checkout-complete-container']",
  },
};
